spring:
    application:
        name: JobManagerBackend

    datasource:
        url: jdbc:postgresql://localhost:5432/
        username: root
        password: root
    jpa:
        properties:
            generate-ddl: true
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
          ddl-auto: update

mail:
    smtp:
        user: xerox6655@gmx.at
        password: gfMe45xhAh9B4Zp
        host: mail.gmx.net
        port: 587
    imap:
        user: xerox6655@gmx.at
        password: gfMe45xhAh9B4Zp
        host: imap.gmx.net
        port: 993