spring:
    application:
        name: JobManagerBackend

    datasource:
        url: jdbc:postgresql://localhost:5432/
        username: root
        password: root
    jpa:
        properties:
            generate-ddl: true
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
          ddl-auto: update

